version: '3'
services:
  webserver:
    container_name: web
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - "./devops/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./devops/nginx/conf.d:/etc/nginx/conf.d"
      - "./src:/var/www/html"
    links:
      - main
      - db
    networks:
      - mynet
    command: [nginx-debug, '-g', 'daemon off;']

  main:
    build:
      context: ./devops/php
    ports:
      - "9000:9000"
    container_name: php
    links:
      - db
    volumes:
      - "./src:/var/www/html"
    networks:
      - mynet
  db:
    container_name: db_promo
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
#      - ./devops/mysql/dump/:/docker-entrypoint-initdb.d
      - ./dbdata/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mydatabase
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
